version: '3.7'

services:
  database:
    image: postgres:13
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - app-network

  movies-admin:
    depends_on:
      - database
    build: .
    volumes:
      - static:/home/movies/static
    env_file:
      - .env
    command: >
      sh -c "
      sleep 10 &&
      python3 manage.py migrate &&
      gunicorn -b 0.0.0.0:8000 config.wsgi app:movies"
    networks:
      - app-network

  server:
    image: nginx:1.20
    depends_on:
      - movies-admin
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/conf:/etc/nginx/conf.d
      - static:/var/www/static
    ports:
      - "80"
    restart: on-failure
    networks:
      - app-network

  move_data:
    build: ./sqlite_to_postgres/.
    command: >
      bash -c "sleep 15
      && python3 load_data.py"
    depends_on:
      - database
      - movies-admin
    networks:
      - app-network

  es:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    depends_on:
      - move_data
    networks:
      - app-network

  redis:
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
    image: redis:6.2.5
    volumes:
      - redisdata:/data
    networks:
      - app-network

  etl:
    build: ./postgres_to_es
    env_file:
      - .env
    volumes:
      - ./postgres_to_es:/etl
    command: tail -f /dev/null
    depends_on:
      - es
      - redis
      - movies-admin
    networks:
      - app-network

volumes:
  es_data:
  redisdata:
  static:
  data:
  db:

networks:
    app-network:
        driver: bridge
